#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CCadmin.Resource", IsApplication=true)]

namespace CCadmin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BlacklistDeleteIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BlacklistPlusIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int DashboardAlertRulesIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int DashboardAlertsIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int DashboardBlacklistIcon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int DashboardDashboardIcon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int DashboardGeneralSettingsIcon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int DashboardImagesIcon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int DashboardTwitterIcon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int GeneralEditIcon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int HeaderDashboardIcon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int LoginBackgroundImage = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int LoginCCIcon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int MainAlertIcon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int MainCCIcon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int MainDashboardDownIcon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int MainDashboardUpIcon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int MainHeaderBackground = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int MainSearchIcon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int MainUserIcon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int TableRowEven = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int TableRowFirst = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int TableRowGradient = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int TableRowOdd = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int TwitterConfigIcon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int TwitterPlusIcon = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001b
			public const int FlyOutContainer = 2131034139;
			
			// aapt resource value: 0x7f050005
			public const int contentContainerFrameLayout = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int contentTableLayout = 2131034121;
			
			// aapt resource value: 0x7f050011
			public const int dashboardAlertRulesLinearLayout = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int dashboardAlertsLinearLayout = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int dashboardBlacklistLinearLayout = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int dashboardContainerLinearLayout = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int dashboardContentLinearLayout = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int dashboardGeneralSettingsLinearLayout = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int dashboardImagesLinearLayout = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int dashboardTwitterLinearLayout = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int headerTitleTextView = 2131034120;
			
			// aapt resource value: 0x7f050019
			public const int loadingLinearLayout = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int loginLoginButton = 2131034138;
			
			// aapt resource value: 0x7f050007
			public const int mainDashboardImageButton = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int mainHeaderLinearLayout = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int rowAlertTextView = 2131034112;
			
			// aapt resource value: 0x7f050015
			public const int rowAuthorImageView = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int rowAuthorTextView = 2131034135;
			
			// aapt resource value: 0x7f050001
			public const int rowCountTextView = 2131034113;
			
			// aapt resource value: 0x7f05001f
			public const int rowDashTextView = 2131034143;
			
			// aapt resource value: 0x7f050002
			public const int rowDateTimeTextView = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int rowDeleteImageButton = 2131034115;
			
			// aapt resource value: 0x7f050014
			public const int rowEditImageButton = 2131034132;
			
			// aapt resource value: 0x7f050020
			public const int rowEmailTextView = 2131034144;
			
			// aapt resource value: 0x7f050016
			public const int rowImageImageView = 2131034134;
			
			// aapt resource value: 0x7f05001e
			public const int rowMobileTextView = 2131034142;
			
			// aapt resource value: 0x7f050018
			public const int rowPromoteImageButton = 2131034136;
			
			// aapt resource value: 0x7f05001c
			public const int rowRuleTextView = 2131034140;
			
			// aapt resource value: 0x7f050012
			public const int rowSettingTextView = 2131034130;
			
			// aapt resource value: 0x7f05001d
			public const int rowTermTextView = 2131034141;
			
			// aapt resource value: 0x7f050021
			public const int rowTextTextView = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int rowTweetTextView = 2131034146;
			
			// aapt resource value: 0x7f050013
			public const int rowValueTextView = 2131034131;
			
			// aapt resource value: 0x7f050004
			public const int rowWordTextView = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AlertsTableRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BlacklistTableRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ContentLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DashboardLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int GeneralTableRow = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ImagesTableRow = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LoadingLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int LoginLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MainLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int RulesTableRow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int TweetsTableRow = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
